version: "3.8"
services:
    web:
        image: jzlatkov/devops-web
        deploy:
          replicas: 5
        ports:
          - 8080:80
        volumes:
          - "/vagrant/DevOps/web:/var/www/html:ro"
        networks:
          - app-network
        depends_on:
          - db
    db:
        image: jzlatkov/devops-db
        networks:
          - app-network
        environment:
            MYSQL_ROOT_PASSWORD: "12345"
networks:

      app-network:
